name: deepsky_bluetooth_android_bridge
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

  deepsky_bluetooth_interface:
    path: ../deepsky_bluetooth_interface

  deepsky_bluetooth_android:
    path: ../../plugins/deepsky_bluetooth_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
